projects:
  WaitLess:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/types/API.ts
        docsFilePath: src/graphql
        region: us-east-1
        apiId: ljnl4elolzbgdfrpodbifolbne
        maxDepth: 2
extensions:
  amplify:
    version: 3
