export const blackish = "#1c1c17"; // fonts
export const blue = "#677e97"; // primary color alt
export const blueGray = "#76828e"; // primary color
export const darkRed = "#580420"; // border, accent
export const red420 = "#420420"; // border, accent
export const sageGray = "#768E8E"; // UNUSED... but could be?
export const tan = "#d7d7ce"; // form background
export const tanOpaque = tan.concat("80"); // list item background
export const whitish = "#e1e1e0"; // background
